version: '3.7'
services:
  tlanalytics:
    image: ghcr.io/tyler71/tl-aws-analytics:latest
    build:
      context: .
    labels:
      caddy: ${hostname}
      caddy.reverse_proxy: "{{ upstreams ${port} }}"
#   ports:
#     - 8080:8501
    volumes:
      - "./data/app:/data"
      - "./app:/app"
    env_file:
      - app.env
    networks:
      - public

networks:
  public:
    external: true
