
services:
  tlanalytics:
    image: ghcr.io/tyler71/tl-aws-analytics:latest
    ports:
      - 80:8080
      - 443:4443
    volumes:
      - app_data:/home/application
    env_file:
      - .env

volumes:
  app_data:
