name: Build image and push to AWS ECR

on:
  push:
    branches:
    - production

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        id:   aws-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Variables
        id:   v
        run: |
          echo "::set-output name=date::$(date '+%m_%d_%Y')"
          echo "::set-output name=reponame::techline-analytics"

      - name: Login to Amazon ECR
        id:   login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Build and push
        uses: docker/build-push-action@v2
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ steps.v.outputs.reponame }}
        with:
          context: .
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ steps.v.outputs.date }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Deploy to App Runner Image
        id: deploy-apprunner
        uses: awslabs/amazon-app-runner-deploy@main
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ steps.v.outputs.reponame }}
        with:
          service: ${{ secrets.APP_RUNNER_SERVICE_NAME }}
          image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ steps.v.outputs.date }}
          access-role-arn: ${{ secrets.ROLE_ARN }}
          region: ${{ secrets.AWS_REGION }}
          cpu : 1
          memory : 2
          wait-for-service-stability: false
      
#      - name: App Runner output
#        run: echo "App runner output ${{ steps.deploy-apprunner.outputs.service-id }}" 
