name: Build / Push AWS ECR; Deploy to AWS Beanstalk

on:
  push:
    branches:
    - none

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        id:   aws-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Variables
        id:   v
        run: |
          echo "::set-output name=date::$(date '+%m_%d_%Y')"
          echo "::set-output name=reponame::$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')"

      - name: Login to Amazon ECR
        id:   login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        env:
          ECR_REGISTRY:   ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ steps.v.outputs.reponame }}
        with:
          context: .
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ steps.v.outputs.date }}
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:build_${{ github.run_number }}
          build-args: |
            SET_GIT_SHA=${{ github.sha }}
          cache-from: type=gha
          cache-to:   type=gha,mode=max

      # Configure deployment package to use AWS repo with image of today's date.
      - name: Generate deployment package
        env:
          ECR_REGISTRY:   ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ steps.v.outputs.reponame }}
        run: |
          cd beanstalk
          sed -i "s;image:.*;image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ steps.v.outputs.date }};" docker-compose.yml
          zip -r ../deploy.zip .

      - name: Upload deploy artifact
        uses: actions/upload-artifact@v2
        with:
          name:           beanstalk-deploy.zip
          path:           ./deploy.zip
          retention-days: 14

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_session_token:                 ${{ github.event.inputs.session_token }}
          aws_access_key:                    ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key:                    ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name:                  ${{ secrets.EB_APP_NAME }}
          environment_name:                  ${{ secrets.EB_ENV_NAME }}
          version_label:                     tl-analytics-source-${{ github.run_number }}
          use_existing_version_if_available: true
          region:                            ${{ secrets.AWS_REGION }}
          existing_bucket_name:              ${{ secrets.EB_BUCKET }}
          wait_for_deployment:               false
          deployment_package:                deploy.zip
