name: Build / Upload Docker ghcr.io

on:
  push:
    branches:
    - dev

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Variables
        id:   v
        run: |
          echo "::set-output name=date::$(date '+%m_%d_%Y')"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/tl-aws-analytics:latest
            ghcr.io/${{ github.actor }}/tl-aws-analytics:${{ steps.v.outputs.date }}
            ghcr.io/${{ github.actor }}/tl-aws-analytics:build_${{ github.run_number }}
          build-args: |
            SET_GIT_SHA=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
